sudo: required
dist: trusty

language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DLORINA_TEST=ON ..
  - make
  - ./test/run_tests

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
