sudo: required
dist: trusty

language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DLORINA_TEST=ON -DLORINA_EXAMPLES=ON ..
  - make run_tests
  - ./test/run_tests

before_install:
  - python3 -m pip install --user cpp-coveralls

after_success:
  - coveralls --gcov-options '\-lp'

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ggcov
      env: COMPILER=g++-7 CXX_STANDARD=17
